import { ApiProperty } from '@nestjs/swagger';
import { IsOptional, IsString } from 'class-validator';

/**
 * Query parameters TikTok sends to the OAuth callback URI.
 *
 * Success case:   ?code=<auth_code>&state=<state_jwt>&scopes=<granted_scopes>
 * Error case:     ?error=<code>&error_description=<msg>&state=<state_jwt>
 *
 * Reference: https://developers.tiktok.com/doc/oauth-user-access-token-management
 */
export class TikTokCallbackQueryDto {
  /** Authorization code to exchange for access/refresh tokens. Present on success. */
  @ApiProperty({ required: false, description: 'TikTok authorization code' })
  @IsOptional()
  @IsString()
  code?: string;

  /**
   * Opaque state value — this implementation uses a short-lived signed JWT
   * containing the authenticated RaaSocial userId, generated by the frontend
   * before redirecting the user to TikTok.
   */
  @ApiProperty({ required: false, description: 'State JWT containing userId' })
  @IsOptional()
  @IsString()
  state?: string;

  /** Comma-separated list of scopes granted by the user. */
  @ApiProperty({ required: false })
  @IsOptional()
  @IsString()
  scopes?: string;

  /** TikTok error code when the user denies authorization. */
  @ApiProperty({ required: false })
  @IsOptional()
  @IsString()
  error?: string;

  /** Human-readable error description from TikTok. */
  @ApiProperty({ required: false })
  @IsOptional()
  @IsString()
  error_description?: string;
}
