import {
  pgTable,
  uuid,
  varchar,
  text,
  timestamp,
  boolean,
  pgEnum,
  json,
} from 'drizzle-orm/pg-core';
import { relations } from 'drizzle-orm';
import { users } from './users.schema';

/**
 * Publishing status of a content calendar post.
 * - DRAFT      : not yet scheduled
 * - SCHEDULED  : approved and queued for future publish
 * - PUBLISHED  : already published on the social platform
 */
export const postStatusEnum = pgEnum('post_status', [
  'DRAFT',
  'SCHEDULED',
  'PUBLISHED',
]);

/**
 * Admin approval status of a content calendar post.
 * - PENDING           : awaiting admin review
 * - APPROVED          : admin approved, ready to schedule/publish
 * - REJECTED          : admin rejected the post
 * - REVISION_REQUIRED : admin requested changes before approval
 */
export const postApprovalStatusEnum = pgEnum('post_approval_status', [
  'PENDING',
  'APPROVED',
  'REJECTED',
  'REVISION_REQUIRED',
]);

/**
 * Social media platforms supported by the content calendar.
 */
export const postPlatformEnum = pgEnum('post_platform', [
  'Instagram',
  'LinkedIn',
  'X / Twitter',
  'TikTok',
  'Facebook',
]);

/**
 * Main content calendar table.
 * Each row represents one scheduled or published social media post
 * created by a customer (user) and subject to admin approval.
 */
export const contentCalendar = pgTable('content_calendar', {
  /** Primary key — random UUID v4. */
  id: uuid('id').primaryKey().defaultRandom(),

  /**
   * The user (customer) who owns this post.
   * Cascade delete: removing a user removes all their posts.
   */
  userId: uuid('user_id')
    .notNull()
    .references(() => users.id, { onDelete: 'cascade' }),

  /** Short title / headline used in the calendar grid. */
  title: varchar('title', { length: 255 }).notNull(),

  /** The main body text / caption of the social post. */
  caption: text('caption').notNull(),

  /** The social media platform this post targets. */
  platform: postPlatformEnum('platform').notNull(),

  /** Publishing status — DRAFT, SCHEDULED, or PUBLISHED. */
  status: postStatusEnum('status').notNull().default('DRAFT'),

  /** Admin approval status — PENDING by default until reviewed. */
  approvalStatus: postApprovalStatusEnum('approval_status')
    .notNull()
    .default('PENDING'),

  /** Optional feedback notes left by the admin (e.g. revision instructions). */
  adminNotes: text('admin_notes'),

  /** When the post is scheduled to be published (null if draft). */
  scheduledAt: timestamp('scheduled_at'),

  /** When the post was actually published (null if not yet published). */
  publishedAt: timestamp('published_at'),

  /** URL to the media asset (image or video) attached to the post. */
  mediaUrl: varchar('media_url', { length: 2048 }),

  /** Hashtags stored as a JSON array of strings. */
  hashtags: json('hashtags').$type<string[]>().default([]),

  /** Whether this post was generated by the AI. */
  aiGenerated: boolean('ai_generated').notNull().default(false),

  /** The suggestion selected by the user for this post. */
  selectedSuggestionId: uuid('selected_suggestion_id'),

  /** Record creation timestamp. */
  createdAt: timestamp('created_at').notNull().defaultNow(),

  /** Record last-update timestamp. */
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
});

/**
 * Drizzle ORM relational mapping: each post belongs to one user.
 */
import { contentSuggestions } from './content-suggestions.schema';

export const contentCalendarRelations = relations(
  contentCalendar,
  ({ one, many }) => ({
    user: one(users, {
      fields: [contentCalendar.userId],
      references: [users.id],
    }),
    selectedSuggestion: one(contentSuggestions, {
      fields: [contentCalendar.selectedSuggestionId],
      references: [contentSuggestions.id],
    }),
    suggestions: many(contentSuggestions),
  }),
);

/** TypeScript type for reading a row from content_calendar. */
export type ContentCalendarPost = typeof contentCalendar.$inferSelect;

/** TypeScript type for inserting a new row into content_calendar. */
export type NewContentCalendarPost = typeof contentCalendar.$inferInsert;

